[package]
name = "laptop_guard"
version = "0.1.0"
edition = "2021"

[dependencies]
battery = "0.7.8"
chrono = "0.4.39"
clap = { version = "4.5.28", features = ["derive"] }
colored = "3.0.0"
regex = "1.11.1"
ureq = "3.0.6"
