name: PR Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  linux:
    name: Rust Code Checks for Linux target
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update to the last Rust stable version
        run: rustup update stable

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy (Linter)
        run: cargo clippy -- -D warnings

      - name: Build project for Linux
        run: cargo build --target x86_64-unknown-linux-gnu

  windows:
    name: Rust Code Checks for Windows target
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update to the last Rust stable version
        run: rustup update stable

      - name: Build project for Windows
        run: cargo build --target x86_64-pc-windows-gnu
